Add 601.Human_Traffic_of_Stadium
SHY-Corp/LeetCode-Solutions pull request #1114
Opened 2020-10-25 05:47 UTC by pikachu28

## Pull Request Template

### What have you Changed(must)

Added solution query to Human Traffic Stadium Problem 

### Issue no.(must) - #1080 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [ ] My file is in the proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [ ] I have named the file as 601.Human_Traffic_of_Stadium.sql
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-10-27 09:34 UTC, pikachu28 commented
@swaingotnochill  plz approve my PR for hacktoberfest : )

2020-10-29 16:52 UTC, Yashica7 requested changes
Please describe what your code does at the beginning of the program

2020-10-30 09:12 UTC, pikachu28 commented
Review the requested changes : )

2020-10-30 12:14 UTC, SSKale1 approved these changes

2020-10-30 12:14 UTC, merged