Added 3 Sum in Java
SHY-Corp/LeetCode-Solutions pull request #1380
Opened 2020-10-30 16:05 UTC by shouvikch97

## Pull Request Template

### What have you Changed(must)
Added 15. 3 Sum in Java

Write here what you have changed in the codebase
Added the code for 3 Sum in Java

### Issue no.(must) - #1311 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [ ] My file is in the proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [ ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-10-30 16:06 UTC, shouvikch97 commented
Please review my PR.

2020-10-31 11:37 UTC, JOKUE2002 requested changes
Please add some documentation describing what the code does / what your approach is

2020-10-31 15:01 UTC, shouvikch97 commented
I have added the documentation.
I hope it helps.
Please review.

2020-10-31 15:47 UTC, JOKUE2002 approved these changes

2020-10-31 15:47 UTC, merged