12. Integer to Roman
SHY-Corp/LeetCode-Solutions pull request #1452
Opened 2020-10-31 08:03 UTC by kajal-puri

## Pull Request Template

### What have you Changed(must)

Added new Python code for Problem 12. Integer to Roman

### Issue no.(must) - #1208 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-10-31 08:04 UTC, kajal-puri commented
@SSKale1 Please have a look and let me know if any changes are required. Thanks!

2020-11-01 00:07 UTC, Yashica7 requested changes
Remove the extra file

2020-11-01 04:20 UTC, kajal-puri commented
@Yashica7 removed the file, let me know!

2020-11-03 05:58 UTC, SSKale1 approved these changes

2020-11-03 05:59 UTC, merged