867. Transpose Matrix
SHY-Corp/LeetCode-Solutions pull request #1567
Opened 2020-11-21 06:27 UTC by Sauravsingh-Rana

## Pull Request Template

### Added a new code to the C++ folder.

Write here what you have changed in the codebase

### Issue no.(must) - #1536 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.

### Self Check(Tick After Making pull Request)

- [ *] This issue was assigned to me if not it will be marked as spam.
- [ *] My file is in the proper folder
- [ *] I am following clean code and Documentation.
- [ *] I have added the title and what program will do first in the file
- [ *] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-11-22 22:13 UTC, Yashica7 requested changes
Please add a description or comments of what your code does

2020-11-23 04:31 UTC, Sauravsingh-Rana commented on C++/867. TransposeMatrix.cpp
> +
`//This Code will help you in Transposing any square matrix.`

2020-11-23 05:47 UTC, Sauravsingh-Rana commented
> Please add a description or comments of what your code does

Thank you @Yashica7 for improvising me. Can you please check now the modified file, if there is anything i forget to add it would be helpful to me.

2020-11-23 18:17 UTC, Yashica7 commented
Looks better, will merge this now

2020-11-23 18:17 UTC, merged

2020-11-25 03:11 UTC, Sauravsingh-Rana commented
> Looks better, will merge this now

Thank you... @Yashica7