Create 532.K-diffPairsInAnArray.cpp
SHY-Corp/LeetCode-Solutions pull request #220
Opened 2020-10-08 08:06 UTC by SHIVANATHRIHARIKRISHNA

## Pull Request Template

### What have you Changed(must)

Added the code for 532.K-diff pairs in an array solution in C++ which is assigned to me @SHIVANATHRIHARIKRISHNA

### Issue no.(must) - 207

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x ] This issue was assigned to me if not it will marked as spam.
- [x ] My file is in proper folder
- [ x] I am following clean code and Documentation.
- [x ] I have added title and what program will do first in the file
- [ x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-10-08 14:23 UTC, SSKale1 requested changes
Add some comments at the beginning of the code to explain what your program is doing.

2020-10-08 14:45 UTC, SHIVANATHRIHARIKRISHNA commented
Added the comment to explain the below code

2020-10-09 05:11 UTC, SSKale1 commented
I'll be removing the 179. LargestNumber.cpp file as it is not a part of this issue.

2020-10-09 05:11 UTC, SSKale1 approved these changes

2020-10-09 05:12 UTC, merged