Create 225.Implement Stack Using Queues
SHY-Corp/LeetCode-Solutions pull request #368
Opened 2020-10-12 08:24 UTC by hjpassion

Stacks and queues are dynamic sets in which the element removed from the set by the DELETE operations is prespecified. Stack implements a LIFO policy, while queue implements FIFO.
Stack supports operations
push (insert)
pop (delete)
Queue supports
enqueue (insert)
dequeue (delete)

## Pull Request Template

### What have you Changed(must)

Write here what you have changed in the codebase

### Issue no.(must) - #325 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [ ] My file is in the proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [ ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-10-12 08:25 UTC, hjpassion commented
please accept my PR sir! @SSKale1 @Yashica7

2020-10-13 04:14 UTC, SSKale1 requested changes
We do not need the pseudocode but the actual working cpp code for this. For this problem everything that the problem solution has a class and the functions for all the operations. As given here https://leetcode.com/problems/implement-stack-using-queues/ .

2020-10-13 05:43 UTC, hjpassion commented
now i have changed the code ! @SSKale1 @Yashica7

2020-10-14 13:04 UTC, SSKale1 approved these changes

2020-10-14 13:04 UTC, merged