Added answers to Q39 , Q 41 in Python
SHY-Corp/LeetCode-Solutions pull request #640
Opened 2020-10-18 18:37 UTC by thebinarybot

## Pull Request Template

### What have you Changed - Added two Python solution files assigned to me

Write here what you have changed in the codebase 
Added file 39.combinationSum.py
Added file 41. firstMissingPositive.py

### Issue no.(must) - 
For 39.combinationSum.py - #604 
For 41. firstMissingPositive.py - #609 

PR will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [ ] My file is in the proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [ ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### README - [How to Contribute](https://github.com/SSKale1/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

2020-10-19 06:23 UTC, Yashica7 requested changes
Please remove the rest of the files that is not assigned to u and add what ur code does as well

2020-10-24 11:56 UTC, SSKale1 commented
@thebinarybot make the requested changes in 24 hours or we'll have to close this PR.

2020-10-25 12:16 UTC, SSKale1 requested changes
Add some comments to explain what your code is doing. And add the .py extension to file 41.

2020-10-30 11:57 UTC, SSKale1 approved these changes

2020-10-30 11:57 UTC, merged